#!/bin/bash

# Generate initial key files for all nodes

. config.sh

if [ -z "$TERRAFORM_STATE_DIR" ]; then
    echo "TERRAFORM_STATE_DIR must be set"
    exit 1
fi


ansible \
    --private-key=/etc/keys/sawtoothlake.pem \
    -i inventory \
    vgroup0 --list-hosts

ansible \
    --private-key=/etc/keys/sawtoothlake.pem \
    -i inventory \
    -b \
    vgroup0 \
    -a "dpkg -r python-sawtooth-validator python-sawtooth-core python-sawtooth-arcade python-sawtooth-mktplace"

#ansible \
#    --private-key=/etc/keys/sawtoothlake.pem \
#    -i inventory \
#    vgroup1 --list-hosts
#
#ansible \
#    --private-key=/etc/keys/sawtoothlake.pem \
#    -i inventory \
#    -b \
#    vgroup1 \
#    -a "dpkg -r python-sawtooth-core python-sawtooth-validator python-sawtooth-arcade"
