#!/bin/bash
set -e

info() {
    echo -e "\033[0;36m\n[--- $1 ---]\n\033[0m"
}

export GNUPGHOME=/data/.gnupg/
stamp=$(date +%F-%H)


info "Downloading archive"
wget https://build.sawtooth.me/view/all/job/Sawtooth-Hyperledger/job/sawtooth-core/job/master/lastSuccessfulBuild/artifact/*zip*/archive.zip -O tmp/$stamp.zip


info "Uncompressing archive"
mkdir tmp/$stamp
unzip -q tmp/$stamp.zip -d tmp/$stamp


info "Adding artifacts to repository"
ls -al tmp/$stamp/archive/build/debs/
aptly repo add nightly tmp/$stamp/archive/build/debs/*/*sawtooth*.deb
info "Creating snapshot"
aptly snapshot create nightly-$stamp from repo nightly
info "Publishing snapshot"
aptly publish switch xenial s3:repo.sawtooth.me:ubuntu/nightly nightly-$stamp

info "Cleanup time"
rm tmp/$stamp.zip
rm -rf tmp/$stamp
