- name: Install cloud-utils
  apt:
    name=cloud-guest-utils

- name: Grow root partition size
  shell: growpart /dev/xvda 1 || true

- name: Resize root partition filesystem
  shell: resize2fs /dev/xvda1

- name: update and upgrade apt packages
  apt:
    update_cache: yes

- name: Install coredumpctl
  apt:
    name: systemd-coredump

- name: Copy coredumpctl service unit file
  copy:
    src: systemd-coredump@.service
    dest: /etc/systemd/system/systemd-coredump@.service
    owner: root
    group: root
    mode: 0644

- name: Restart systemd-coredump and reload systemd units
  systemd:
      state: restarted
      name: systemd-coredump.socket
      daemon_reload: yes

- name: Set ulimit for core dumps
  pam_limits: domain='*' limit_type='-' limit_item=core value='unlimited'

- name: Reload sysctl values
  shell: sysctl --system

- name: Set Hostname
  hostname: name={{ ec2_tag_Name }} # Needs to be changed if not using ec2

- name: Install pip3
  apt:
      name=python3-pip
      state=present
      force=yes

- name: Download Sawtooth Repo Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 44FC67F19B2466EA

- name: Add Sawtooth Repo
  apt_repository:
    repo: "deb http://repo.sawtooth.me/{{ sawtooth_repo }} xenial universe"
    state: present
    filename: sawtooth-lake
    update_cache: yes

- name: Perform dist-upgrade
  apt:
    upgrade: dist

- name: Install Sawtooth
  apt:
    name={{ item }}
    state=present
    force=yes
  with_items: "{{ sawtooth_packages }}"

- name: Clean packages directory
  file: path=/tmp/sawtooth-packages state=absent

- name: Create packages directory
  file: path=/tmp/sawtooth-packages state=directory

- name: Download .zip from PR job
  get_url:
    url: "https://build.sawtooth.me/view/all/job/Sawtooth-Hyperledger/job/sawtooth-raft/job/master/lastSuccessfulBuild/artifact/ci/sawtooth-raft_0.1.1-dev1_amd64.deb"
    dest: /tmp/sawtooth-packages

- name: Install PoET Sawtooth packages
  shell: >
          ls -1 && \
          dpkg -i \
          sawtooth-raft_0.1.1-dev1_amd64.deb
  args:
    chdir: /tmp/sawtooth-packages


- name: Configure Sawtooth Services
  template:
      src: "{{ item }}.j2"
      dest: "/etc/default/{{ item }}"
  with_items: "{{ sawtooth_services }}"

- name: Copy config files
  template:
      src: "{{ item }}.j2"
      dest: "/etc/sawtooth/{{ item }}"
  with_items: "{{ sawtooth_configs }}"

- name: Configure Sawtooth Logging
  template:
      src: "log_config.yaml.j2"
      dest: "/etc/sawtooth/log_config.yaml"

- name: Configure Sawtooth Rest API Logging
  template:
      src: "rest_api_log_config.yaml.j2"
      dest: "/etc/sawtooth/rest_api_log_config.yaml"

- name: Install telegraf
  apt:
      deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.4.1-1_amd64.deb

- name: Configure telegraf
  template:
      src: "telegraf.conf.j2"
      dest: "/etc/telegraf/telegraf.conf"

- name: Restart telegraf and reload systemd units
  systemd:
      state: restarted
      name: telegraf
      daemon_reload: yes

