---

  - name: Include vars
    include_vars:
      file: sawtooth.yaml

  - name: Update existing packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Download Sawtooth Repo Key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: "{{ sawtooth_repo_key_id }}"

  - name: Add Sawtooth Repo
    apt_repository:
      repo: "deb http://repo.sawtooth.me/{{ sawtooth_repo }} xenial universe"
      state: present
      filename: sawtooth-lake
      update_cache: yes

  - name: Install Sawtooth
    apt:
      name={{ item }}
      state=present
      force=yes
    with_items: "{{ sawtooth_packages }}"

  - name: Copy special validator service file
    copy:
      src: sawtooth-validator.service
      dest: /lib/systemd/system/sawtooth-validator.service
      owner: root
      group: root
      mode: 0644

  - name: Copy sawtooth-setup script
    copy: 
      src: sawtooth-setup
      dest: /sbin/sawtooth-setup
      owner: root
      group: root
      mode: 0755

  - name: Copy setup service unit file
    copy:
      src: sawtooth-setup.service
      dest: /lib/systemd/system/sawtooth-setup.service
      owner: root
      group: root
      mode: 0644

  - name: Create wants directory for sawtooth-setup
    file:
      path: /etc/systemd/system/sawtooth-setup.service.wants
      state: directory
      mode: 0755

  - name: Symlink sawtooth-setup wants services
    file:
      src: /lib/systemd/system/{{ item }}.service
      dest: /etc/systemd/system/sawtooth-setup.service.wants/{{ item }}.service
      state: link
    with_items: "{{ sawtooth_services }}"

  - name: Systemctl daemon reload
    command: systemctl daemon-reload

  - name: Enable setup service
    systemd:
      name: sawtooth-setup.service
      enabled: yes
      masked: no

  - name: Clean up authorized_keys
    shell: find / -name "authorized_keys" -exec rm -f {} \;
