---
# Playbook for installing and configuring sawtooth validator.

- name: Setup Validators
  hosts: "{{ network_name }}"
  roles:
    - nuc
  become: yes
  any_errors_fatal: yes

#- include: fetch_keys.yaml
