---
- name: Generate Keys
  hosts: "{{ network_name }}"
  tasks:
    - command: "sawadm keygen"
      args:
        creates: "/etc/sawtooth/keys/validator.*"
  become: yes

- name: Bootstrap Genesis Node
  hosts:  "{{ play_hosts[0] }}"
  tasks:
    - name: "Create Config Genesis Batch"
      command: "sawset genesis -k /etc/sawtooth/keys/validator.priv -o /home/sawtooth/config-genesis.batch"
      args:
        creates: "/home/sawtooth/config-genesis.batch"

    - name: "Set Consensus Algorithm"
      shell: >
              sawset proposal create -k /etc/sawtooth/keys/validator.priv
              sawtooth.consensus.algorithm=poet
              sawtooth.poet.report_public_key_pem="$(cat /etc/sawtooth/ias_rk_pub.pem)"
              sawtooth.poet.valid_enclave_measurements=$(poet enclave --enclave-module sgx measurement)
              sawtooth.poet.valid_enclave_basenames=$(poet enclave --enclave-module sgx basename)
              sawtooth.poet.enclave_module_name=sawtooth_poet_sgx.poet_enclave_sgx.poet_enclave
              -o /home/sawtooth/config.batch
      args:
        creates: "/home/sawtooth/config.batch"

    - name: "PoET settings"
      shell: >
              sawset proposal create -k /etc/sawtooth/keys/validator.priv
              sawtooth.poet.target_wait_time=30
              sawtooth.poet.initial_wait_time=300
              sawtooth.publisher.max_batches_per_block=500
              sawtooth.poet.ztest_minimum_win_count=10000
              sawtooth.poet.key_block_claim_limit=100000
              -o /home/sawtooth/poet_setting.batch
      args:
        creates: "/home/sawtooth/poet_setting.batch"

    - name: "Create Poet Genesis Batch"
      command: "poet registration create -k /etc/sawtooth/keys/validator.priv --enclave-module sgx -o /home/sawtooth/poet.batch"
      args:
        creates: "/home/sawtooth/poet.batch"

    - name: "Run Sawtooth Genesis"
      shell: "sawadm genesis /home/sawtooth/config-genesis.batch /home/sawtooth/config.batch /home/sawtooth/poet.batch /home/sawtooth/poet_setting.batch && cp /var/lib/sawtooth/genesis.batch /home/sawtooth/genesis.batch"
      args:
        creates: "/home/sawtooth/genesis.batch"

    - name: "Generate User Keys"
      shell: "sawtooth keygen"
      args:
        creates: "/home/sawtooth/.sawtooth/keys/sawtooth.priv"

  become: yes
  become_user: sawtooth

- name: Start Sawtooth Network
  hosts: "{{ network_name }}"
  tasks:
    - name: "Start Sawtooth Services"
      systemd:
        state: started
        name: "{{ item }}"
      with_items: "{{ sawtooth_services }}"
  become: yes

- include: setup_onchain_permissions.yaml
